######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 24 21:15:52 2014
######################################################################

TEMPLATE = app
TARGET = MineSweeper 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
SOURCES += main.cpp \
    thefield.cpp    \
    mainwindow.cpp  \
    highscore.cpp

HEADERS += thefield.h   \
    mainwindow.h        \
    highscore.h

OBJECTS_DIR = .obj/
MOC_DIR = .moc/

